name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      release-tag:
        description: '要发布的Release标签（例如 v1.0.0）'
        required: true   # 设为必填，避免空值
        default: ''
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish X to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: CodeMiracle.MagicBox
          installers-regex: '\.exe$' # Only .exe files
          token: ${{ secrets.WINGET_TOKEN }}
